/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apple_watch_series_5.glb -T 
Files: apple_watch_series_5.glb [6.35MB] > C:\Users\admin\Desktop\3dapple\mac-project\public\models\apple_watch_series_5-transformed.glb [976.98KB] (85%)
Author: atomle (https://sketchfab.com/atomle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-series-5-16950208bdf041f193c31d3b4a0ac15a
Title: Apple watch series 5
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/apple_watch_series_5-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ToJTXgljlhhqitR.geometry} material={materials.LiBdTcnHkZvFfBu} scale={0.033} />
      <mesh geometry={nodes.fWLGcfnLpXnhehz.geometry} material={materials.GdUNwQJEkZeKMrn} scale={0.033} />
      <mesh geometry={nodes.aEQvkfzeWvwzYAe.geometry} material={materials.JbkKnNDeFOFjmsi} scale={0.033} />
      <mesh geometry={nodes.sEZkXDXAzFzaCpi.geometry} material={materials.JAXIvIljFWpqimH} scale={0.033} />
      <mesh geometry={nodes.NIYNwKgmPYCkzpx.geometry} material={materials.RfziScXwNjFOjTf} scale={0.033} />
      <mesh geometry={nodes.BrmhLaxyDmhbhXA.geometry} material={materials.KwQHVIjAaOBvYOl} scale={0.033} />
      <mesh geometry={nodes.tqQTKXmBvXiXuUi.geometry} material={materials.iDKPrezlRKAMsXJ} scale={0.033} />
      <mesh geometry={nodes.yTjoxDvwbAPZygY.geometry} material={materials.QGhrBgCXrJDNcrC} scale={0.033} />
      <mesh geometry={nodes.yHafeexXAiPytbW.geometry} material={materials.FqtwwTANGDActcI} scale={0.033} />
      <mesh geometry={nodes.KeqqEyvZchDDdlP.geometry} material={materials.AjFlTFrWzhywymA} scale={0.033} />
      <mesh geometry={nodes.skbFGMQxPawHdOT.geometry} material={materials.xYqzIToOcTBbEzp} scale={0.033} />
      <mesh geometry={nodes.ajDgJcjsZTQAtOL.geometry} material={materials.rcZoXGfqfnZjYLv} scale={0.033} />
      <mesh geometry={nodes.wflxnmxxYXvnLxp.geometry} material={materials.YRNmAgRITIuwDMU} scale={0.033} />
      <mesh geometry={nodes.ePnvfhsUgYTHLdP.geometry} material={materials.iVwMRUBqdpoOFmg} scale={0.033} />
      <mesh geometry={nodes.aynleugQGbyNYsa.geometry} material={materials.kFNgmsjtRAxVPtH} scale={0.033} />
      <mesh geometry={nodes.HyRzdvVQMwELnwT.geometry} material={materials.upTfEpgNFxflqtf} scale={0.033} />
      <mesh geometry={nodes.bvsBShDTmaTjbXM.geometry} material={materials.YpOtGMmrQbktABJ} scale={0.033} />
      <mesh geometry={nodes.lnDzpNAJfMDjFms.geometry} material={materials.qxhxiJVpuwSrYLW} scale={0.033} />
      <mesh geometry={nodes.lrTNGAQkeHccJph.geometry} material={materials.ycVxkCIsnetKUsw} scale={0.033} />
      <mesh geometry={nodes.jChLaKiiqDISJhc.geometry} material={materials.JUrNntQLbxHnFtO} scale={0.033} />
      <mesh geometry={nodes.DzgfJtxUfpgExsF.geometry} material={materials.mUXcyUQCxEEJdiO} scale={0.033} />
      <mesh geometry={nodes.MBrZKZXWsvHIcZQ.geometry} material={materials.JBuGosClPcYrSry} scale={0.033} />
      <mesh geometry={nodes.acJwQeGdNxQWEyd.geometry} material={materials.OEDmdMOTgdNMXOP} scale={0.033} />
      <mesh geometry={nodes.mcMtSAOyQxOEEfl.geometry} material={materials.sJrbBWzziZrNyXB} scale={0.033} />
      <mesh geometry={nodes.qbgXzfcPGFYiUnN.geometry} material={materials.FBAtOQrXrgOoPNd} scale={0.033} />
      <mesh geometry={nodes.dXSXlyOaLTQHAnn.geometry} material={materials.gMZhwegVXLXWOLd} scale={0.033} />
    </group>
  )
}

useGLTF.preload('/models/apple_watch_series_5-transformed.glb')
