/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apple_watch_ultra_2.glb -T 
Files: apple_watch_ultra_2.glb [15.34MB] > C:\Users\admin\Desktop\3dapple\mac-project\public\models\apple_watch_ultra_2-transformed.glb [2.22MB] (86%)
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-ultra-2-f33263c457664b43909200c5ed5e6fa2
Title: Apple Watch Ultra 2
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/apple_watch_ultra_2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.NONHYSHLUQzoyez.geometry} material={materials.JSFaTttTQosHtdR} scale={0.01} />
      <mesh geometry={nodes.nUikKFsvZdptvXF.geometry} material={materials.edhWAPEBZsqCLTg} scale={0.01} />
      <mesh geometry={nodes.VHnHbLOyhEXLvWA.geometry} material={materials.edYkGGAdRWeopLP} scale={0.01} />
      <mesh geometry={nodes.DCiPNWQGULbWNNE.geometry} material={materials.AGtKlWnOInmqNQI} scale={0.01} />
      <mesh geometry={nodes.LbodUHJUCGqowCz.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh geometry={nodes.BMKlRAQYzgiNCrq_1.geometry} material={materials.yKAKXxwHUkGVYpC} scale={0.01} />
      <mesh geometry={nodes.joGEgikMuDmcVlT.geometry} material={materials.GXPSJdzybTrBefY} scale={0.01} />
      <mesh geometry={nodes.LMTUXYhSYYJrnsy_0.geometry} material={materials.LMTUXYhSYYJrnsy_0} scale={0.01} />
      <mesh geometry={nodes.HoKUOQkmlXGGrun.geometry} material={materials.YtajTVWccmKRZBL} scale={0.01} />
      <mesh geometry={nodes.dAobUVRiwHRHUwW.geometry} material={materials.GvXrALMIeaGmIJo} scale={0.01} />
      <mesh geometry={nodes.odYscQETIRVJKxR.geometry} material={materials.KjETpDnldvdbNBw} scale={0.01} />
      <mesh geometry={nodes.qHpopFXBXmHOUYS.geometry} material={materials.VJcIxaYCeMHzzAJ} scale={0.01} />
      <mesh geometry={nodes.AXTiAWNANGWNPZh.geometry} material={materials.vqobCvtAVyNLbeh} scale={0.01} />
      <mesh geometry={nodes.jGEqmDFMbHJGHIM.geometry} material={materials.NfRpqTxrWQxoAIy} scale={0.01} />
      <mesh geometry={nodes.OFYufNMwvtHmxdH.geometry} material={materials.hSvQcziHKpXubDY} scale={0.01} />
      <mesh geometry={nodes.dEKwzvajmGpjRpl.geometry} material={materials.yXTwmSCvToGuMDP} scale={0.01} />
      <mesh geometry={nodes.ggBokQJJgYcckom.geometry} material={materials.IvaXKlaVZetAvuj} scale={0.01} />
      <mesh geometry={nodes.SWRxiioprGlZKOq.geometry} material={materials.PaletteMaterial002} scale={0.01} />
      <mesh geometry={nodes.AnKriXdRdkHvVgp.geometry} material={materials.PaletteMaterial003} scale={0.01} />
      <mesh geometry={nodes.VqmyRLxQuilpALX.geometry} material={materials.PaletteMaterial004} scale={0.01} />
      <mesh geometry={nodes.FiiGAhWFHdUxhDn.geometry} material={materials.boERCOkfaeYKPmb} scale={0.01} />
      <mesh geometry={nodes.pVqLnJdxODmWtTg.geometry} material={materials.troyYZUIqRYbiDX} scale={0.01} />
      <mesh geometry={nodes.fOvUJMAYMqVGOTV.geometry} material={materials.FsJfKVbzNLXJeBa} scale={0.01} />
      <mesh geometry={nodes.ffjHNJzYIjDziJe.geometry} material={materials.sTxeXXVKohXeDJU} scale={0.01} />
      <mesh geometry={nodes.EZmdWXCjqrUDeoX.geometry} material={materials.lgIBGhMXHpTEcfq} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/apple_watch_ultra_2-transformed.glb')
