/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cameras.glb -T 
Files: cameras.glb [68.52MB] > C:\Users\admin\Desktop\3dapple\mac-project\public\models\cameras-transformed.glb [4.05MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/cameras-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_id3138.geometry} material={materials['4927']} position={[0.303, 0.146, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3144.geometry} material={materials['4931']} position={[0.303, 0.146, 0.416]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3145.geometry} material={materials['4290']} position={[0.303, 0.146, 0.418]} rotation={[0, -0.004, 0]} scale={[0.042, 0.04, 0]} />
      <mesh geometry={nodes.mesh_id3142.geometry} material={materials['4945']} position={[0.303, 0.146, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3143.geometry} material={materials['4935']} position={[0.303, 0.146, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3140.geometry} material={materials['4937']} position={[0.303, 0.146, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4383.geometry} material={materials['4943']} position={[0.577, -0.036, 0.411]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4380.geometry} material={materials['4947']} position={[0.577, -0.036, 0.407]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4373.geometry} material={materials['4999']} position={[0.576, -0.037, 0.408]} rotation={[0, -0.004, 0]} scale={0} />
      <mesh geometry={nodes.mesh_id4354.geometry} material={materials['4951']} position={[0.556, -0.013, 0.398]} rotation={[0, -0.004, 0]} scale={[0.107, 0.115, 0.007]} />
      <mesh geometry={nodes.mesh_id4375.geometry} material={materials['5003']} position={[0.576, -0.037, 0.407]} rotation={[0, -0.004, 0]} scale={0} />
      <mesh geometry={nodes.mesh_id4434.geometry} material={materials['4959']} position={[0.667, -0.014, 0.398]} rotation={[0, -0.004, 0]} scale={[0.107, 0.115, 0.007]} />
      <mesh geometry={nodes.mesh_id4436.geometry} material={materials['4961']} position={[0.691, 0.025, 0.402]} rotation={[Math.PI / 2, 0, -3.137]} scale={0} />
      <mesh geometry={nodes.mesh_id4461.geometry} material={materials['4963']} position={[0.687, -0.037, 0.411]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4471.geometry} material={materials['4965']} position={[0.687, -0.037, 0.407]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4437.geometry} material={materials['4971']} position={[0.691, 0.025, 0.404]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4438.geometry} material={materials['4346']} position={[0.691, 0.025, 0.405]} rotation={[0, -0.004, 0]} scale={[0.013, 0.013, 0.001]} />
      <mesh geometry={nodes.mesh_id4442.geometry} material={materials['4973']} position={[0.64, -0.04, 0.402]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4443.geometry} material={materials['4975']} position={[0.64, -0.04, 0.404]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4371.geometry} material={materials['4977']} position={[0.529, -0.039, 0.404]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4352.geometry} material={materials['4979']} position={[0.556, -0.013, 0.397]} rotation={[0, -0.004, 0]} scale={[0.108, 0.116, 0.006]} />
      <mesh geometry={nodes.mesh_id3880.geometry} material={materials['4981']} position={[0.129, 0.115, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3881.geometry} material={materials['4983']} position={[0.129, 0.115, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3892.geometry} material={materials['4464']} position={[0.138, 0.084, 0.41]} rotation={[0, -0.004, 0]} scale={[0.002, 0.001, 0]} />
      <mesh geometry={nodes.mesh_id4628.geometry} material={materials['4987']} position={[0.133, 0.024, 0.404]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3895.geometry} material={materials['4351']} position={[0.138, 0.081, 0.41]} rotation={[0, -0.004, 0]} scale={[0.002, 0.001, 0]} />
      <mesh geometry={nodes.mesh_id3896.geometry} material={materials['4344']} position={[0.136, 0.081, 0.41]} rotation={[0, -0.004, 0]} scale={[0.002, 0.001, 0]} />
      <mesh geometry={nodes.mesh_id3897.geometry} material={materials['4353']} position={[0.136, 0.083, 0.41]} rotation={[0, -0.004, 0]} scale={[0.002, 0.001, 0]} />
      <mesh geometry={nodes.mesh_id3891.geometry} material={materials['4989']} position={[0.138, 0.082, 0.409]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3894.geometry} material={materials['4400']} position={[0.138, 0.083, 0.41]} rotation={[0, -0.004, 0]} scale={[0.002, 0.001, 0]} />
      <mesh geometry={nodes.mesh_id3886.geometry} material={materials['4991']} position={[0.129, 0.115, 0.416]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3357.geometry} material={materials['4993']} position={[0.192, 0.148, 0.416]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5465.geometry} material={materials['5031']} position={[0.581, -0.112, 0.405]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3790.geometry} material={materials['5059']} position={[0.686, 0.112, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3347.geometry} material={materials['5067']} position={[0.242, 0.115, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3370.geometry} material={materials['5069']} position={[0.241, 0.159, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3374.geometry} material={materials['5075']} position={[0.252, 0.083, 0.409]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3916.geometry} material={materials['5079']} position={[0.078, 0.086, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4548.geometry} material={materials['5103']} position={[0.2, 0.015, 0.411]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5739.geometry} material={materials['5129']} position={[0.245, -0.138, 0.405]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5735.geometry} material={materials['5131']} position={[0.245, -0.109, 0.405]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5907.geometry} material={materials['5135']} position={[0.086, -0.11, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5932.geometry} material={materials['5137']} position={[0.086, -0.168, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5935.geometry} material={materials['5143']} position={[0.086, -0.168, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4607.geometry} material={materials['5147']} position={[0.081, -0.042, 0.404]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4539.geometry} material={materials['5169']} position={[0.24, -0.037, 0.411]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5726.geometry} material={materials['5175']} position={[0.198, -0.109, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5744.geometry} material={materials['5183']} position={[0.198, -0.167, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5754.geometry} material={materials['5185']} position={[0.198, -0.167, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5477.geometry} material={materials['5197']} position={[0.534, -0.17, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5471.geometry} material={materials['5203']} position={[0.581, -0.141, 0.405]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5457.geometry} material={materials['5205']} position={[0.534, -0.112, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3632.geometry} material={materials['5251']} position={[0.525, 0.087, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3777.geometry} material={materials['5257']} position={[0.636, 0.144, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3782.geometry} material={materials['5259']} position={[0.636, 0.144, 0.416]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3364.geometry} material={materials['4995']} position={[0.192, 0.147, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3365.geometry} material={materials['4997']} position={[0.192, 0.147, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3331.geometry} material={materials['5009']} position={[0.192, 0.087, 0.416]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3807.geometry} material={materials['5025']} position={[0.685, 0.155, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5545.geometry} material={materials['5209']} position={[0.469, -0.11, 0.405]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5554.geometry} material={materials['5037']} position={[0.446, -0.14, 0.399]} rotation={[0, -0.004, 0]} scale={[0.108, 0.116, 0.006]} />
      <mesh geometry={nodes.mesh_id5556.geometry} material={materials['5207']} position={[0.447, -0.14, 0.399]} rotation={[0, -0.004, 0]} scale={[0.107, 0.115, 0.007]} />
      <mesh geometry={nodes.mesh_id5558.geometry} material={materials['5275']} position={[0.422, -0.111, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5565.geometry} material={materials['5043']} position={[0.422, -0.111, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4991.geometry} material={materials['5049']} position={[0.648, -0.112, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3789.geometry} material={materials['5057']} position={[0.686, 0.112, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3793.geometry} material={materials['5061']} position={[0.686, 0.112, 0.416]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4541.geometry} material={materials['5073']} position={[0.244, 0.025, 0.404]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id3929.geometry} material={materials['5083']} position={[0.104, 0.116, 0.402]} rotation={[0, -0.004, 0]} scale={[0.107, 0.115, 0.007]} />
      <mesh geometry={nodes.mesh_id3924.geometry} material={materials['5085']} position={[0.104, 0.116, 0.402]} rotation={[0, -0.004, 0]} scale={[0.108, 0.116, 0.007]} />
      <mesh geometry={nodes.mesh_id3919.geometry} material={materials['5087']} position={[0.078, 0.086, 0.416]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4083.geometry} material={materials['5095']} position={[0.352, -0.037, 0.411]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4545.geometry} material={materials['5097']} position={[0.219, -0.014, 0.397]} rotation={[0, -0.004, 0]} scale={[0.108, 0.116, 0.006]} />
      <mesh geometry={nodes.mesh_id4544.geometry} material={materials['5099']} position={[0.219, -0.013, 0.398]} rotation={[0, -0.004, 0]} scale={[0.107, 0.115, 0.007]} />
      <mesh geometry={nodes.mesh_id4550.geometry} material={materials['5101']} position={[0.2, 0.015, 0.407]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4059.geometry} material={materials['5105']} position={[0.331, -0.013, 0.398]} rotation={[0, -0.004, 0]} scale={[0.107, 0.115, 0.007]} />
      <mesh geometry={nodes.mesh_id4060.geometry} material={materials['5107']} position={[0.331, -0.014, 0.397]} rotation={[0, -0.004, 0]} scale={[0.108, 0.116, 0.006]} />
      <mesh geometry={nodes.mesh_id4049.geometry} material={materials['5267']} position={[0.304, -0.04, 0.404]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5635.geometry} material={materials['5111']} position={[0.309, -0.11, 0.412]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5643.geometry} material={materials['5113']} position={[0.309, -0.11, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5644.geometry} material={materials['5119']} position={[0.334, -0.139, 0.399]} rotation={[0, -0.004, 0]} scale={[0.108, 0.116, 0.006]} />
      <mesh geometry={nodes.mesh_id5469.geometry} material={materials['5195']} position={[0.558, -0.141, 0.399]} rotation={[0, -0.004, 0]} scale={[0.107, 0.115, 0.007]} />
      <mesh geometry={nodes.mesh_id5906.geometry} material={materials['5133']} position={[0.086, -0.11, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4615.geometry} material={materials['5149']} position={[0.129, -0.038, 0.407]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5920.geometry} material={materials['5155']} position={[0.133, -0.109, 0.403]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id5452.geometry} material={materials['5201']} position={[0.534, -0.113, 0.408]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4181.geometry} material={materials['5273']} position={[0.465, -0.036, 0.407]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
      <mesh geometry={nodes.mesh_id4351.geometry} material={materials['5289']} position={[0.537, 0.016, 0.411]} rotation={[Math.PI / 2, 0, 0.004]} scale={0} />
    </group>
  )
}

useGLTF.preload('/models/cameras-transformed.glb')
