/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphneModel.glb -T 
Files: iphneModel.glb [2.75MB] > C:\Users\admin\Desktop\3dapple\mac-project\public\models\iphneModel-transformed.glb [210.73KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/iphneModel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.004, 2.83, 0.004]}>
        <mesh geometry={nodes.Plane027.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Plane027_1.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.Lens_glass.geometry} material={materials.lens} position={[-0.694, 4.178, 0.189]} />
      <mesh geometry={nodes.screw.geometry} material={materials.PaletteMaterial002} position={[-0.221, 0.036, -0.051]} />
      <mesh geometry={nodes.sensor_flash.geometry} material={materials.sensor_flash} position={[0.009, 3.907, 0.072]} />
    </group>
  )
}

useGLTF.preload('/models/iphneModel-transformed.glb')
