/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iphone17.glb -T 
Files: iphone17.glb [9.59MB] > C:\Users\admin\Desktop\3dapple\mac-project\public\models\iphone17-transformed.glb [334.12KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/iphone17-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.004']} position={[0.609, 1.661, -0.12]} rotation={[0, Math.PI / 2, 0]} scale={0.882} />
      <mesh geometry={nodes.defaultMaterial001.geometry} material={materials['Material.002']} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.Glass_Camera_Logo} position={[-0.004, -0.012, -0.055]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.Plastic} position={[0.609, 1.661, -0.108]} rotation={[-Math.PI / 2, 0, 0]} scale={0.027} />
      <mesh geometry={nodes.defaultMaterial004.geometry} material={materials.Screen_Rim} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.Grill_USB} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.Camera_Pixel_Glass_002} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial007.geometry} material={materials.Camera_Pixel__002} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial009.geometry} material={materials.Rim_Buttons} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial010.geometry} material={materials.Flash_Glass_002} position={[-0.621, 1.715, -0.092]} rotation={[-Math.PI / 2, 0, 0]} scale={0.029} />
      <mesh geometry={nodes.defaultMaterial011.geometry} material={materials.Flash_002} position={[-0.621, 1.715, -0.08]} rotation={[-Math.PI / 2, 0, 0]} scale={0.029} />
      <mesh geometry={nodes.defaultMaterial012.geometry} material={materials.Screen_BG} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial013.geometry} material={materials.Screw} position={[0, 0, 0.043]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.defaultMaterial014.geometry} material={materials.Screen_Glass} position={[0.609, 1.661, -0.14]} rotation={[-Math.PI / 2, 0, 0]} scale={0.027} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[0, 0, 0.126]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.827} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.003']} position={[0, 0, 0.126]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.827} />
    </group>
  )
}

useGLTF.preload('/models/iphone17-transformed.glb')
